version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_PATH}/nginx/certs:/etc/nginx/certs:ro
      - ${NGINX_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PATH}/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
    - webproxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - ${NGINX_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PATH}/certs:/etc/nginx/certs:rw
      - ${NGINX_PATH}/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

networks:
  webproxy:
